added true to docker compose run

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,10 +33,12 @@ jobs:
       - name: Run unit tests
         if: success() || failure()
         run: |
-         docker-compose run --rm unit-tests
+         docker-compose run --rm unit-tests || true
          if grep -q '"status": "failed"' ./allure-results/*.json; then
+           echo "Recording failed tests"
            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
          else
+           echo "Recording success tests"
            echo "TESTS_STATUS=success" >> $GITHUB_ENV
          fi
 
